# placeholders can be found at https://www.spigotmc.org/resources/tab-1-8-x-1-13-2-reborn.57806/
# plugin also supports PlaceholderAPI

change-nametag-prefix-suffix: true #Warning! Disabling will break sorting of players in tablist!
change-tablist-prefix-suffix: true
enable-header-footer: true

#20 ticks = 1 second
#if you want to use animated prefix/suffix, you need to decrease this to 1 or 2 (depending on fastest animation) to make them work
nametag-refresh-interval-ticks: 1200
tablist-refresh-interval-ticks: 1200

#using very low interval to allow animations to work as expected
#if you aren't using any animations, increase this to save cpu
header-footer-refresh-interval-ticks: 1

#VERY EXPERIMENTAL !
#IF YOU EXPERIENCE ANY ISSUES PM ME ON SPIGOT
unlimited-nametag-prefix-suffix-mode:
  enabled: false

header:
  - "&eWankercraft.org"
#  - "&6%rank%"
#  - "&7Welcome &7%nick%"
#  - "&7Online players: &f%online%"
  - "&6Online staff: &e%staffonline%"
#  - "&aPing: &2&n%ping%&r &ams"
  - ""
  - "%animation:MyAnimation1%"
# - "%animation:versions%" #requires ViaVersion or ProtocolSupport
footer:
  - "%animation:MyAnimation1%"
  - ""
  - "&6wankercraft.org"
  - "&6mc.wankercraft.org"
  - "&6https://discord.gg/QSpTYCe"
  
#SERVERS 1.9+
#this plugin overrides any other attemps to change collision rule, so it needs to be configured here
enable-collision: true

#PING - ping of players
#HEARTS - health of players
#DEATHS - total amount of deaths of players
#CUSTOM - custom configurable placeholder
#NONE - disabled
tablist-objective: PING
tablist-objective-custom-value: "%some_placeholderapi_placeholder%"

#preventing players in spectator gamemode from appearing at the bottom of tablist
#the spectator will still see himself incorrectly, but will look correctly to others
#disabled by default so you don't think it's obvious and every plugin has this
do-not-move-spectators: false

#also used to find main group if a player is in more than 1 (hello LuckPerms users)
group-sorting-priority-list:
  - "Owner"
  - "Admin"
  - "Mod"
  - "Member"
#  - "Builderr"
#  - "Premium"
#  - "Player"
  - "default"

#used for %staffonline% variable
staff-groups:
  - "Admin"
  - "Mod"
  - "Owner"
  - "Moderator"
  - "Helper"

#better showing of %rank% value
rank-aliases:
#  Admin: "&4&lADMIN"
#  Mod: "&b&lMOD"
#  VIP: "&6&lPREMIUM"
#  Member: ""
#  Ultra: "&b&lULTRA"
#  Legend: "&a&lLEGEND"
#  Titan: "&c&lTITAN"
#  Youtuber: "&c&lYOUTUBE"
  
  #default setting for other groups
  _OTHER_: "%vault-prefix%"


# - list of options
#tabprefix = prefix in tablist with no known limit of characters
#tagprefix = prefix above player's character (no limit if unlimited-nametag-prefix-suffix-mode is ENABLED)
#tabsuffix = suffix in tablist with no known limit of characters
#tagsuffix = suffix above player's character (no limit if unlimited-nametag-prefix-suffix-mode is ENABLED)
#header = per player or per group header
#footer = per player or per group footer
#belowname = a line under player's name (REQUIRES unlimited-nametag-prefix-suffix-mode ENABLED)
#abovename = a line above player's name (REQUIRES unlimited-nametag-prefix-suffix-mode ENABLED)
#customtabname = change a display name of player in tablist
#customtagname = change a display name of player in name tag (requires unlimited-nametag-prefix-suffix-mode enabled)

#you don't need to use all of these values, you can delete the empty values to not have this config full of "spam"
#if no personal (or per group) header/footer is set, the default one from above will be used

Groups:
  Owner:
#    tabprefix: "&0&l[&a&lOwner&0&l] &a"
#    tagprefix: "&2&lOwner &a"
    header:
#      - "ur server man"
    footer:
#      - "welcome"
  Admin:
#    tabprefix: "&0&l[&4&lAdmin&0&l] &1"
    tabsuffix: " &b[Admin]"
#    tagprefix: "%animation:admin_prefix%"
    tagsuffix: " &b[Admin]"
  Mod:
#    tabprefix: "&0&l[&7&lPlayer&0&l] &3"
#    tagprefix: "&2&lPlayer &3"
  Member:
#    tabprefix: ""
#    tabsuffix: " [Member]"
#    tagprefix: ""


    
  #any other group not defined above
  _OTHER_:
    tabprefix: "%rank% "
    tagprefix: "%rank% "
    tabsuffix: "%afk%"
    tagsuffix: "%afk%"
    customtabname: "%essentialsnick%"
    customtagname: "%essentialsnick%"

#personal settings, override group settings
Users:
  md_5:
    tabprefix: "&6&lSpigot &a"
    tagprefix: "&6&lDev &a"
    tabsuffix: ""
    tagsuffix: ""
    abovename: "Hi"
    belowname: "There"
    customtabname: "MessageDigest5"
    customtagname: "MessageDigest5"
    
#list of worlds with different settings than default, other worlds will use settings from above
per-world-settings:
  wankercraft:
#    header:
#      - "an example of world with custom"
#    footer:
#      - "&7[wankercraft]"
    Groups:
      Member:
        tabsuffix: " &7[wankercraft]"
#        header:
#          - "ur server man"
#        footer:
#          - "welcome"
#      Admin:
#        tabprefix: "&2&lAdmin &1&l"
#        tagprefix: "&2&lAdmin &1&l"
#      Mod:
#        tabprefix: "&5&lPlayer &3&l"
#        tagprefix: "&5&lPlayer &3&l"
#    Users:
#      Player1:
#        tabprefix: ""
#        tagprefix: ""
#        tabsuffix: ""
#        tagsuffix: ""

#setting output of some placeholders        
placeholders:
  deluxetag-yes: "< %value% >"
  deluxetag-no: "&oNo Tag :("
  faction-yes: "< %value% >"
  faction-no: "&2Wilderness"
  afk-yes: " &4*&4&lAFK&4*&r"
  afk-no: ""
  # %date%
  date-format: "dd.MM.yyyy"
  # %time%, pick one
  time-format: "[HH:mm:ss / h:mm a]"
  
disable-features-in-worlds:
  header-footer:
    - disabledworld
  tablist-names:
    - disabledworld
  nametag:
    - disabledworld
  tablist-objective:
    - disabledworld
  bossbar:
    - disabledworld
